### ISSUE TITLE
Could this be AMP compatible?

### ISSUE THREAD

**Issue by PaulHale** [zsugabubus/vim-commentr#2]
Hi, 

Thanks for creating this. I'm fairly new to nvim and am looking for a way to quickly comment out a single line of CSS within HTML AMP files.

```
Be default if I hit <leader>cc when over some css I get 

<!-- my css --> where I would like  /* my css */

My .html file is AMP and my inner CSS scripts starts with <style amp-custom>
```

I know this is a none standard case but am just wondering if it would be possible to implement?

**Comment by zsugabubus** [comment]
Do you use plugin for syntax highlighting for "amp" files, or they are just "html" files? What does `set filetype?` say?

**Comment by zsugabubus** [comment]
Thanks for reporting, 812e228 should solve your issue. Please checkout master and let me know if it still occurs.

`commentr` guesses file type from syntax elements and I made a silly mistake where I just missed the first tokens, so for example from `cssStyle` it missed `css`.

**Comment by zsugabubus** [comment]
@PaulHale, are you still facing the issue?

**Comment by zsugabubus** [comment]
Close because of no feedback and it's possibly fixed.
